language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: bIvHvWQlxB6SlOM++KS9u2BO1wPtTQHBNlLJuAA2XLB9AYDiYdBVAW/dXe2Fxf1qyywvooQaPkjWpqYst/11g85Z5OHcRdrntAq5zV6K0umhTlPwEWYPW1fXdvLnY7esILiFOdGIgZpvjhb04aZUtuplBJuNTNyMA5v7UIZKWvf+z0BKwwRPnfoDGaGLFlwPPQYtojXWmVoKWZY0TsZ49FGoohAdf4xusIW1EE7Zs4qPaAG+OozXwgxLQN31SC9irdXGzvRv3WnN0SUSux0bsyAJbnDCr2/NCBUU5Rr/LdOj6IPpE2pVDBJOYRMOAHEHkjHYHXNZjqWCmbDdXR3exkUIVv4ld6MbOz7TJXkpBu4qjAGBvZ49hmpXafq6zsxxMR6oI/2pwMlEJU/WXrlGPDqP71dJBDR0ajL5OjKlogoli5cQeiOfhL1JwA2F1pm5JYomB7EYouIuCG8aUy4Adh6phn7mU9thIhe0d8Hyc3+iKPb7qksCXEXzIGlUhBGvSG+EfdIjiNqnz2zt6hsc1HlBB26JrlmNMpVPAkQ0NiaTY/NlMM7hultZZ3bo68otwNfuI0xBEHOgmytKaRs4igrayCR4JB85ecUx+jbbp5spvPg4UZ/egIoGBnYIfYJ/dfwtkH2gOU7IdB7Pc/sP0PLQgjbr7iPWQRSYc92wq00=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
